name: Release Lazy (Deb Package)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deb:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: amd64
            deb_arch: amd64
            asset: lazy_amd64.deb

          - arch: arm64
            deb_arch: arm64
            asset: lazy_arm64.deb

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -e .

      - name: Configure PyInstaller hidden imports
        run: |
          echo "HIDDEN_IMPORTS=--hidden-import=keyring.backends.SecretService --hidden-import=shellingham.posix" >> $GITHUB_ENV

      - name: Build standalone binary
        run: |
          pyinstaller \
            --name lazy \
            --onefile \
            $HIDDEN_IMPORTS \
            src/lazy/__main__.py

      - name: Install fpm
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby ruby-dev
          sudo gem install fpm

      - name: Build deb package
        run: |
          fpm \
            -s dir \
            -t deb \
            -n lazy \
            -v ${GITHUB_REF_NAME#v} \
            -a ${{ matrix.deb_arch }} \
            --license LGPL-3.0 \
            --maintainer "YardRat0117 <yardrat0117@gmail.com>"
            --url "https://github.com/YangShu232-Snow/Learning_at_ZJU_third_client" \
            --description "Lazy ZJU Client (CLI + WebUI) is a third-party client for Learning at ZJU." \
            --deb-no-default-config-files \
            dist/lazy=/usr/bin/lazy

          mv *.deb ${{ matrix.asset }}

      - name: Upload build artifact (manual run)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: lazy-${{ matrix.arch }}
          path: ${{ matrix.asset }}

      - name: Upload release asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.asset }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

